### PR TITLE
support typescript

### PR DESCRIPTION
**Pull request by 0x0a0d**
add declaration to support using with typescript
I'm not master with typescript so I hope someone can help me review this

### CODE REVIEW

**Comment by Jimbly** [comment]
I'm not sure there's anyone familiar with TypeScript who would see this PR, but I don't think it can possibly hurt anything, so would be happy to merge it.  Does this file need to get included in what gets published to NPM to be useful, I'm assuming?

**Comment by 0x0a0d** [comment]
It doesn’t need to include anything else to publish.
Typescript help developers to know what module exported, typeof params,…

**Comment by Jimbly** [comment]
I meant, does this new file, `http-parser.d.ts`, need to get published to NPM to be useful, or just needs to be in the repository?  I'm assuming it needs to get published, just need to publish a new version if so.

**Comment by 0x0a0d** [comment]
Just publish a new version (`npm version patch`)

**Comment by Jimbly** [comment]
Just publishing a new version does nothing unless that file is included / not ignored, but it sounds like it needs to be included, so will do so.

**Comment by Jimbly** [comment]
Added the file to `package.json`:`files` and published to NPM as v0.5.4

**Pull request merged**
