### PR TITLE
OnHeadersCompleteParser should accept void return

### PR DESCRIPTION
**Pull request by 0x0a0d**

### CODE REVIEW

**Comment by 0x0a0d** [comment]
@Jimbly could you release this :D

**Comment by Jimbly** [comment]
This was merged and released the day it was submitted in f37d4e4926ab9309aabe7fa35fef88df0d5290e6, about 4 months ago.

**Comment by Jimbly** [comment]
Oh, sorry, my bad, looks like that was released right _before_ this was merged!  Will release, sorry about missing this =)

**Comment by Jimbly** [comment]
Published to NPM as v0.5.6

**Pull request merged**
