### PR TITLE
Update to node 6.3.0

### LINKED ISSUE #23: Test failed on node v6
```
> http-parser-js@0.4.2 test ~/http-parser-js
> python tests/test.py && node tests/iojs/test-http-parser-durability.js

=== release test-http-header-response-splitting ===                        
Path: parallel/test-http-header-response-splitting
~/http-parser-js/http-parser.js:106
      throw err;
      ^

TypeError: The header content contains invalid characters
    at storeHeader (_http_outgoing.js:309:11)
    at ServerResponse.OutgoingMessage._storeHeader (_http_outgoing.js:223:9)
    at ServerResponse.writeHead (_http_server.js:218:8)
    at reply (~/http-parser-js/tests/parallel/test-http-header-response-splitting.js:14:11)
    at Server.<anonymous> (~/http-parser-js/tests/parallel/test-http-header-response-splitting.js:42:7)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at HTTPParser.HEADER (~/http-parser-js/http-parser.js:292:58)
Command: node ~/http-parser-js/tests/parallel/test-http-header-response-splitting.js
=== release test-http-upgrade-agent ===                                        
Path: parallel/test-http-upgrade-agent
Command: node ~/http-parser-js/tests/parallel/test-http-upgrade-agent.js
--- TIMEOUT ---
=== release test-http-upgrade-client ===                    
Path: parallel/test-http-upgrade-client
Command: node ~/http-parser-js/tests/parallel/test-http-upgrade-client.js
--- TIMEOUT ---
=== release test-http-url.parse-only-support-http-https-protocol ===           
Path: parallel/test-http-url.parse-only-support-http-https-protocol
assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: 'Protocol "file:" not supported. Expected "http:"' === 'Protocol "file:" not supported. Expected "http:".'
    at Object.<anonymous> (~/http-parser-js/tests/parallel/test-http-url.parse-only-support-http-https-protocol.js:12:12)
    at expectedException (assert.js:299:19)
    at _throws (assert.js:345:8)
    at Function.assert.throws (assert.js:354:3)
    at Object.<anonymous> (~/http-parser-js/tests/parallel/test-http-url.parse-only-support-http-https-protocol.js:8:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
Command: node ~/http-parser-js/tests/parallel/test-http-url.parse-only-support-http-https-protocol.js
=== release test-http-write-head ===                                          
Path: parallel/test-http-write-head
~/http-parser-js/http-parser.js:106
      throw err;
      ^
AssertionError: '"value" required in setHeader("foo", value)' == '`value` required in setHeader("foo", value).'
    at Server.<anonymous> (~/http-parser-js/tests/parallel/test-http-write-head.js:28:12)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at HTTPParser.HEADER (~/http-parser-js/http-parser.js:292:58)
    at HTTPParser.execute (~/http-parser-js/http-parser.js:100:27)
    at Socket.socketOnData (_http_server.js:366:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
Command: node ~/http-parser-js/tests/parallel/test-http-write-head.js
[02:20|% 100|+ 140|-   5]: Done                                
npm ERR! Test failed.  See above for more details.
``

### PR DESCRIPTION
**Pull request by jscissr**
I pulled in the newest tests from node and updated the parser so that all tests pass. This likely fixes #23.

### CODE REVIEW

**Comment by Jimbly** [comment]
Great, thanks!

**Comment by jscissr** [comment]
Could you please publish to npm? Thanks!

**Comment by Jimbly** [comment]
Hmm... I can't, actually.  Looks like the current NPM only allows you to log in with usernames which are entirely lowercase, and I have a capital letter in mine -_-.  I've followed some advice and contacted NPM support to fix my account, but it might be a bit before I can log in again, perhaps @creationix can publish what is in master to NPM? =)

**Comment by creationix** [comment]
Ok, published 8ee9ae7c04d509c5a6d60caba70f4e7639a40f3c to npm as `http-parser-js@0.4.3`

**Pull request merged**
