### PR TITLE
Complete the parser for a HTTP request when no request body. 

### PR DESCRIPTION
**Pull request by kainz**
As documented in 00b17fd.

### CODE REVIEW

**Comment by Jimbly** [comment]
I'm a little rusty on this code (and what http clients do...), but is it not possible for a request to come in which has no transfer-encoding, no content-length, but with connection: close and we need to read the body until the connection closes?  Or does that kind of situation require transfer-encoding: chunked or something?

I think @lrowe made some related changes a while back and might be able to also review this code.

This repo really needs some test cases now that people seem to be using it... =)

**Comment by jscissr** [comment]
At the moment I'm working on some bigger changes to httpparser.js, including adding tests from node.js and io.js.
Not all tests pass yet, but this issue is already solved, and many other bugs. I will probably finish this in a few days and make a pull request.

**Comment by Jimbly** [comment]
Version 0.3.0 is now published which should resolve this issue as well. @kainz, please give it a try

**Comment by kainz** [comment]
Thanks @jscissr and @Jimbly!  I will test this out with my bag of hacks on top of hipache and see how it works.  I should be able to test this out tonight/tomorrow. I'll post my success or lack thereof.

**Comment by kainz** [comment]
So to verify, 0.3.0 works fine in my tests.  TYVM.

**Pull request closed without merging**
