### PR TITLE
missing http method source

### PR DESCRIPTION
**Pull request by masx200**
https://github.com/nodejs/node/blob/5fad0b93667ffc6e4def52996b9529ac99b26319/deps/llhttp/include/llhttp.h#L155

### CODE REVIEW

**Comment by Jimbly** [comment]
I think these maybe need to stay in the same order, or the `methods.indexOf()` is going to return different values than before.  Looks like everything after `UNLINK` in the code you referenced is new, maybe let's just copy all of the new ones in?

**Comment by masx200** [comment]
> I think these maybe need to stay in the same order, or the `methods.indexOf()` is going to return different values than before. Looks like everything after `UNLINK` in the code you referenced is new, maybe let's just copy all of the new ones in?

ok.done

**Comment by Jimbly** [comment]
Can we copy all of the new ones in, up through `HTTP_FLUSH`?

**Comment by masx200** [comment]
This is all http.METHODS has, and none of the other methods are http methods.

**Pull request merged**
