### PR TITLE
add encoding options

### PR DESCRIPTION
**Pull request by magicode**
for  none ascii encoding headers

``` javascript
process.binding('http_parser').HTTPParser = require('http-parser-js').HTTPParser;
require('http-parser-js').HTTPParser.encoding = 'binary';
```

### CODE REVIEW

**Comment by Jimbly** [comment]
This looks like it's probably fine, but, out of curiosity, does Node's HTTP Parser handle this at all?  Also, if this feature is valuable to you, you may want to add a test to ensure it continues functioning in future releases.  Something like https://github.com/creationix/http-parser-js/blob/master/tests/parallel/test-http-blank-header.js should be very easy to modify to test this code.

**Comment by jscissr** [comment]
I'm not sure about this.

HTTP allows "any 8-bit sequence of data" in some headers, but the encoding is not defined. According to [this](http://stackoverflow.com/a/4410331), anything other than ASCII should be treated as "opaque data". It is recommended to only send headers with ASCII characters.

On the Node side, "binary" encoding is actually [deprecated](https://nodejs.org/api/buffer.html#buffer_buffer).

Preferably you (@magicode) shouldn't be receiving non-ASCII headers in the first place. 
Could you explain why you need that feature?

**Comment by Jimbly** [comment]
Because binary is "deprecated", the "right" way might be to use a Buffer instead of a string in this case, since it's opaque binary data, however I'd be worried that basically nothing else in the stack is going to handle header values which are Buffers, so binary encoding is probably the way to go.  The binary encoding is [probably never going away](https://groups.google.com/d/msg/nodejs/GNVDEEc__ow/S0jXdMx7Y7oJ) (and its trivial to emulate), despite being deprecated, since it's incredibly useful in cases like this where the preferred/efficient way (Buffers) just doesn't work.

I agree, no one "should" be receiving non-ASCII headers, but the whole reason I got involved in node-http-parser was very similar (we were receiving invalid HTTP headers, an the Node http parser would just crash, and we absolutely needed to handle them anyway).  We can't fix the crappy software that has already been released upon the internet.

@magicode , if you're building something new, not trying to deal with existing cruft, there's definitely better ways (base64-encoded strings is a common place to start).

**Comment by Jimbly** [comment]
@magicode Still willing to discuss merging this, if there's a compelling reason for it, and, preferably, if you add a simple test as well.

**Pull request closed without merging**
