### PR TITLE
Test on LTS and current node version

### PR DESCRIPTION
**Pull request by Jimbly**
It's failing on Node v6 on my current system, let's see if Travis CI agrees...

### CODE REVIEW

**Comment by Jimbly** [comment]
@jscissr tests are now passing on latest node, and still failing on node 4.x.  I'm not sure if we care or not, as the tests are pretty closely coupled to node versions - not sure if there's a chance this means the library has stopped working on Node 4.x though?

**Comment by jscissr** [comment]
One reason the tests fail on node 4 is because `Buffer.alloc` was only introduced in node 6. For testing on node 4, it is necessary to use the tests from node 4. If you like, I could make a PR to do that. It'd mean having a separate folder for v4 tests and making `npm test` decide which tests to run.

**Comment by Jimbly** [comment]
I *think* that's probably overkill, as long as we're reasonably certain that it still works on the versions of Node which people are still using it on =).

**Comment by jscissr** [comment]
I quickly tested it and the tests passed, so LTS is not broken. :smile:

**Comment by Jimbly** [comment]
Okay, great, we'll leave the tests running on just node 6.x for now.

**Pull request closed without merging**
