### PR TITLE
Use Dependabot to update GitHub Actions

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes

- Create a `dependabot.yml` config file

## Context

When you merge the current PR, the following will happen:

1. Dependabot will start checking for GitHub Action runner updates from Monday through Friday, not on weekends
2. If an update is found, Dependabot will open a PR
3. Read the changelog, and check if the GitHub Action is a stable release or unstable release
4. If you close the PR, Dependabot will ignore that specific version.
5. If you merge the PR you're up-to-date again.

By default Dependabot adds a label `dependencies` to the PRs it creates.
If you don't want any labels to be created, let me know and I'll turn that off for you.

I can of course turn down the frequency of update checks to a weekly or monthly run.

I hope you like this, if not, feel free to close the PR. 👍 

## Documentation

> Actions are often updated with bug fixes and new features to make automated processes more reliable, faster, and safer. When you enable Dependabot version updates for GitHub Actions, Dependabot will help ensure that references to actions in a repository's workflow.yml file are kept up to date. For each action in the file, Dependabot checks the action's reference (typically a version number or commit identifier associated with the action) against the latest version. If a more recent version of the action is available, Dependabot will send you a pull request that updates the reference in the workflow file to the latest version. 

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot

### CODE REVIEW

**Comment by Jimbly** [comment]
My experience with dependabot is it generates a ton of unwanted noise for projects not in active development.  The GitHub actions look super simple and shouldn't actually ever need changing, other than when we add support for a new major Node version, right?  This repo gets changes closer to yearly than monthly, so updating the actions more frequently than changes are made is kind of a waste of effort/attention, I think.

**Comment by HonkingGoose** [comment]
GitHub themselves have this to say about the need to update the Actions:

> Actions are often updated with bug fixes and new features to make automated processes more reliable, faster, and safer.

The current versioning scheme denotes that the GitHub Action runner should use the latest release in the `v2` branch:

https://github.com/creationix/http-parser-js/blob/52c37dba1225d4e34ff8723a5e95938d50ae0cc8/.github/workflows/node-v12.yaml#L24

You won't get any notification when there's a new release in the `v3` branch for `actions/checkout`.
So you would need to manually check from time to time if the actions you use have a new major release.

---

>  The GitHub actions look super simple and shouldn't actually ever need changing, other than when we add support for a new major Node version, right? 

When you want to run tests on a newer version of Node, you can just put the newer Node version into the test matrix here:

https://github.com/creationix/http-parser-js/blob/52c37dba1225d4e34ff8723a5e95938d50ae0cc8/.github/workflows/node.yaml#L21

---

> This repo gets changes closer to yearly than monthly, so updating the actions more frequently than changes are made is kind of a waste of effort/attention, I think.

You can also check the actions manually whenever you make a new release, and check if there's a new major version of the runners then.

**Comment by HonkingGoose** [comment]
## Research into using `v2` tag:

Well I did some research, turns out that the `actions/checkout@v2` tag points to the latest `v2.x.x` release.
You can see the current tags here: https://github.com/actions/checkout/tags
`v2` and `v2.3.4` point to the same commit hash: `5a4ac90`.

Updating the `v2` tag to point to the latest release is a manual job for them, so they might forget to point `v2` to the latest release commit.

## Pro/con relying on `v2` tag alone:

- It's hands off.
- No noise from Dependabot.
- You will not get prompted to update to `v3`.
- You rely on maintainers to point current stable tag to latest stable release.
- You will not get prompted to read the changelogs.
- You don't know what version you're actually running.

## Pro/con using Dependabot to update tag:

- It requires you to update by hand via the Dependabot PR.
- Noise from Dependabot update PR.
- You will get a PR to update to a new major version (`v3`).
- Dependabot will not forget to update you to a newer tag.
- You can read the changelogs for the update.
- You are quite sure of what version you're using.

## Conclusion

You can use my findings to decide what you like best: rely on manual tagging updates, or use a bot to get updates.

**Comment by Jimbly** [comment]
I think we should be fine pointing at `v2`, but we can leave this PR around in case it causes issues and we want to switch to the bot.

**Comment by HonkingGoose** [comment]
I'll close this PR, as I don't think you want to use Dependabot to update your GitHub Actions for now. 😄 

You could try Renovate bot instead, as you can tell Renovate to only propose updates for major version bumps (`actions/checkout@v2` -> `actions/checkout@v3`). This way you're only ever bothered by the bot when there's a new major release (which won't be very often). I can help you get setup with Renovate bot on this repository, if you'd like.

Or you can ignore the honking of this goose, and check for action updates manually once in a while. That's valid as well.

**Pull request closed without merging**
